In [1]:
from warnings import filterwarnings 
filterwarnings('ignore')

In [2]:
import matplotlib.pyplot as plt 
import seaborn as sns
import pandas as pd 
import numpy as np 

%matplotlib inline 

In [3]:
df = pd.read_csv('insurance.csv')

In [4]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [6]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [7]:
df['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [8]:
from sklearn.preprocessing import OrdinalEncoder
ohe = OrdinalEncoder()

In [9]:
ordinal  = ohe.fit_transform(df[['sex', 'region', 'smoker']])

In [10]:
ordinal

array([[0., 3., 1.],
       [1., 2., 0.],
       [1., 2., 0.],
       ...,
       [0., 2., 0.],
       [0., 3., 0.],
       [0., 1., 1.]])

In [12]:
ohe.get_feature_names_out()

array(['sex', 'region', 'smoker'], dtype=object)

In [11]:
encode_df = pd.DataFrame(data=ordinal,columns=ohe.get_feature_names_out())

In [12]:
encode_df['sex'].unique()

array([0., 1.])

In [13]:
encode_df['region'].unique()

array([3., 2., 1., 0.])

In [14]:
encode_df['smoker'].unique()

array([1., 0.])

In [15]:
df = df.drop(df[['sex','region','smoker']],axis=1)

In [16]:
df.head()

age     bmi  children      charges
0   19  27.900         0  16884.92400
1   18  33.770         1   1725.55230
2   28  33.000         3   4449.46200
3   33  22.705         0  21984.47061
4   32  28.880         0   3866.85520

In [17]:
encode_df.head()

sex  region  smoker
0  0.0     3.0     1.0
1  1.0     2.0     0.0
2  1.0     2.0     0.0
3  1.0     1.0     0.0
4  1.0     1.0     0.0

In [18]:
final_df = pd.concat([df,encode_df],axis=1)

In [19]:
final_df

age     bmi  children      charges  sex  region  smoker
0      19  27.900         0  16884.92400  0.0     3.0     1.0
1      18  33.770         1   1725.55230  1.0     2.0     0.0
2      28  33.000         3   4449.46200  1.0     2.0     0.0
3      33  22.705         0  21984.47061  1.0     1.0     0.0
4      32  28.880         0   3866.85520  1.0     1.0     0.0
...   ...     ...       ...          ...  ...     ...     ...
1333   50  30.970         3  10600.54830  1.0     1.0     0.0
1334   18  31.920         0   2205.98080  0.0     0.0     0.0
1335   18  36.850         0   1629.83350  0.0     2.0     0.0
1336   21  25.800         0   2007.94500  0.0     3.0     0.0
1337   61  29.070         0  29141.36030  0.0     1.0     1.0

[1338 rows x 7 columns]

In [20]:
final_df.columns

Index(['age', 'bmi', 'children', 'charges', 'sex', 'region', 'smoker'], dtype='object')

# Seperate The Independent(X) and Dependent(Y) 

In [21]:
X = final_df[['age', 'bmi', 'children', 'smoker', 'sex', 'region']]

y = final_df['charges']

In [22]:
X.head()

age     bmi  children  smoker  sex  region
0   19  27.900         0     1.0  0.0     3.0
1   18  33.770         1     0.0  1.0     2.0
2   28  33.000         3     0.0  1.0     2.0
3   33  22.705         0     0.0  1.0     1.0
4   32  28.880         0     0.0  1.0     1.0

In [23]:
y.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

## Divide the dataset into train test

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test =  train_test_split(X,y, test_size=0.20, random_state=42)

In [25]:
X_train.shape , X_test.shape

((1070, 6), (268, 6))

In [26]:
y_train.shape, y_test.shape

((1070,), (268,))

## Feature Scaling

In [27]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [29]:
scaled_Xtrain =  scaler.fit_transform(X_train)

In [31]:
scaled_Xtrain

array([[ 0.47222651, -1.75652513,  0.73433626, -0.50874702, -1.0246016 ,
        -0.45611589],
       [ 0.54331294, -1.03308239, -0.91119211, -0.50874702, -1.0246016 ,
        -1.35325561],
       [ 0.8987451 , -0.94368672, -0.91119211, -0.50874702, -1.0246016 ,
         0.44102382],
       ...,
       [ 1.3252637 , -0.89153925, -0.91119211, -0.50874702,  0.97598911,
        -1.35325561],
       [-0.16755139,  2.82086429,  0.73433626,  1.96561348, -1.0246016 ,
         1.33816354],
       [ 1.1120044 , -0.10932713, -0.91119211, -0.50874702,  0.97598911,
         1.33816354]])

In [47]:
scaled_Xtest = scaler.transform(X_test)

In [48]:
scaled_Xtest

array([[ 0.45859585, -0.93715188,  0.82250933, -0.50233101, -0.95618289,
        -1.45410926],
       [-0.18713281, -0.16752679, -0.89961958, -0.50233101, -0.95618289,
        -0.51280182],
       [ 1.82180078, -0.66551949, -0.89961958,  1.99071921, -0.95618289,
        -0.51280182],
       ...,
       [-0.04363755, -0.48443124, -0.03855512, -0.50233101,  1.04582503,
        -1.45410926],
       [ 1.1043245 ,  2.59486336, -0.89961958,  1.99071921, -0.95618289,
         0.42850563],
       [ 0.88908162,  0.49646348, -0.03855512, -0.50233101, -0.95618289,
         1.36981308]])

## Model Training

In [49]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [50]:
model.fit(scaled_Xtrain,y_train)

LinearRegression()

In [51]:
model.intercept_

13346.089736364485

In [52]:
model.coef_

array([ 3.61610865e+03,  2.02830858e+03,  5.16662566e+02,  9.55714338e+03,
       -9.39295411e+00, -3.02387980e+02])

# Perfomance Metrics

In [53]:
Y_pred = model.predict(scaled_Xtest)

In [54]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

mse = mean_squared_error(Y_pred,y_test)
mae = mean_absolute_error(Y_pred,y_test)
rmse = np.sqrt(mse)

In [55]:
print(mse)
print(mae)
print(rmse)

33638710.48270799
4186.562998121062
5799.888833650865


In [56]:
from sklearn.metrics import r2_score

result = r2_score(Y_pred,y_test)
result

0.7117703539369977

## Adjust R2

In [57]:
1 - (1-result) * (len(y_test)-1) / (len(y_test)-X_test.shape[1] - 1)

0.7051443850619862